spring:
 application:
    name: self-management
 datasource:
   url: jdbc:postgresql://localhost:5433/automobile
   username: postgres
   password: postgres
 jpa:
  hibernate:
    ddl-auto: none 
  show-sql: true
  properties:
   hibernate:
    format_sql: true
    dialect: org.hibernate.dialect.PostgreSQLDialect
server.port: 8080   
swagger.api.host: localhost:8080
springfox:
  documentation:
    enabled: true


